[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['cd backend && npm ci --production']

[phases.build]
cmds = ['echo "No build phase needed"']

[start]
cmd = 'cd backend && node server.js'
